name: Test PR on Flix Release

on:
  pull_request:
    branches: [ master ]

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.5.0
        with:
          java-version: 17
          distribution: zulu
      - uses: SebRollen/toml-action@v1.0.2
        id: read_toml
        with:
          file: 'flix.toml'
          field: 'package.flix'
      - run: |
          # download Flix JAR
          curl -L https://github.com/flix/flix/releases/download/v${{steps.read_toml.output.value}}/flix.jar > flix.jar

          # run tests
          java -jar flix.jar test --github-key ${{ github.token }}